### ISSUE TITLE
The old parameter syntax `{param}` is no longer supported. Please use `$param` instead.

### ISSUE THREAD

**Issue by msaubier** [grails/gorm-neo4j#449]
I'm working on upgrading a Grails 4 application to Grails 5.  Neo4j is used for the database.  As part of that effort, we want to provide support for neo4j v4+ since v3.5 is end of life.  We are using GORM v7.2.1 and neo4j Java driver v4.4.5.  Java 11 is installed on our test machine.  When we simply call the save() method of a domain class, we receive an error complaining about old, unsupported syntax that GORM is generating.  Is this a bug or is there a different version of the neo4j java driver we should be using?

```
org.neo4j.driver.exceptions.ClientException: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 23 (offset: 22))
   CREATE (n:AppVersion {props}) RETURN ID(n) as id
```

**Comment by puneetbehl** [comment]
Thank you for reporting the issue. 

I have spent a few hours looking into it where I think this can be changed with updating [Neo4jGormStaticApi.groovy](https://github.com/grails/gorm-neo4j/blob/7.3.x/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/api/Neo4jGormStaticApi.groovy#L501). However, updating from v3.5 to v4+ is a major upgrade and may require few more changes. I am currently working on some other items but I will plan to include it as part of next minor update (probably v7.4)

**Comment by msaubier** [comment]
Thanks, @puneetbehl.  Do you have an estimate of when the fix might be available?

**Comment by puneetbehl** [comment]
I am busy with Grails 5.2 and Groovy 3.0.11 update. It seems to me a major upgrade GORM Neo4J project to support v4+ and since 3.5 is already EOL we will soon work on it. But, I am not sure if I will be able to attend to it in next 2 weeks. Meanwhile, I would appreciate if someone could help with the upgrade. Otherwise, I will do it myself when I work on it.

**Comment by msaubier** [comment]
Is there an updated timeframe on when this issue will be addressed?

**Comment by AlbertHjy** [comment]
We are facing the same issue. Is there any workaround before the issue is fixed?

**Comment by msaubier** [comment]
Can we please get an update on when this issue will be addressed?  They have already released Neo4j v5 and v3 is no longer available for download directly from their site.

**Comment by msaubier** [comment]
Do you have an update on when this issue will be addressed?  This is a major issue for our application, so any update would be greatly appreciated.

**Comment by puneetbehl** [comment]
I will try to look into this next week. Thanks!

**Comment by msaubier** [comment]
Thank you, Puneet.  Much appreciated!

**Comment by msaubier** [comment]
Hi @puneetbehl, any update on the progress of this effort and when it might be completed?

**Comment by puneetbehl** [comment]
I am very busy with other items right now and do not have time to look into it. I will be happy to plan out the release quickly if someone is willing to help out with update. Otherwise, I will get back to it once I have some bandwidth. You could also explore our paid support option [here](https://grails.org/support.html)
