### ISSUE TITLE
Proxy not loading correctly when using executeCypher or find

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#51]
Trying to load an object this way:
```
Player player = Player.find("MATCH (n:Player) WHERE n.name = {name} RETURN n", params)
```
or this way
```
Player player = Player.executeCypher("MATCH (n:Player) WHERE n.name = {name} RETURN n", params) as Player
```
when trying to access a related object's id it's returning a wrong one. In this case player.application.id is the same as player.id. This doesn't happen when you load the object with GORM finders or get.
You can reproduce this by downloading the project at https://github.com/mburak/sampleapp, branch 'wrong-proxy'.
1 - Start up the application on an empty db.
2 - Call rest api 'http://localhost:8080/player/checkIds

**Comment by graemerocher** [comment]
This is by design. Unlike a SQL database there is no foreign key column to reference an association, so a query is created of the node using its own id in order to establish the inverse side of the relationship without needing to do a prior `OPTIONAL MATCH` should to retrieve the id. 

This way GORM for Neo4j produces more efficient queries. Granted I understand the confusion with regards to the `id` of the proxy not being the exact id of the inverse node, but that is the cost of producing more efficient queries.
