### ISSUE TITLE
UniqueConstraint, Inheritance and Abstract Class

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#98]
Ticket related (https://github.com/grails/gorm-neo4j/issues/97)

I changed the example to reproduce this other problem that we have now. This is the structure:

`(abstract) A <-- B <-- C`

`A` class has a property called name. `B` class has another property. And `C` class has the `constraint name unique:true`

The difference from the previous example is that `A` class is abstract.

**Problem**
If you have a c object instance of C class which `name='c name'` and you want to save c1 object instance of C class which `name='c name'` (I mean, same name), I will have an exception (Neo4jException) because the criteria was built in UniqueConstraint didn't found other C object with the same name.

![screenshot from 2018-10-11 10-57-09](https://user-images.githubusercontent.com/5392638/46809935-f4e6bd00-cd45-11e8-9e5f-176d8ed7251d.png)

Here is the sample app: https://github.com/AmaliaMV/gorm-uniqueConstraint

The versions I am using are:
```
grailsVersion=3.3.8
gormVersion=6.1.11.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by jameskleeh** [comment]
@AmaliaMV This is happening because the `A` label is not created for the instance. When the query is executed to determine if the unique constraint is valid, it uses `A` because that is the domain where the property exists.

@graemerocher We can either add a label for the abstract entity by changing the logic here (https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/GraphPersistentEntity.groovy#L607), or in the constraint class don't choose an abstract class to query. I don't think the latter is the correct solution since it would miss other descendants.

```
B extends A
C extends A
D extends C
```
When validating D, if we ignored abstracts, then the query would execute on C, which would miss records in B.

Thoughts?

**Comment by graemerocher** [comment]
another option is to allow the assignment of additional labels in the mapping block

**Comment by jameskleeh** [comment]
@AmaliaMV I've added an option you can configure in the mapping section. It is true by default for normal domains, and false by default for abstract domains.

```
static mapping = {
    autoLabel true
}
```

Can be added to the abstract domain to cause the domain label to be added to subclass records. That will allow the issue you've described here to work as expected. Let me know if this works for you

**Comment by AmaliaMV** [comment]
@jameskleeh , thanks! it's working.
